name: "dev-build"

on:
  workflow_dispatch

jobs:
  build-win:
    name: Build Windows (${{ matrix.job.target }})
    permissions: write-all
    runs-on: windows-latest
    strategy:
      fail-fast: false
      matrix:
        job:
          - { os: windows-latest, target: x86_64-pc-windows-gnu }
          - { os: windows-latest, target: x86_64-pc-windows-msvc }
    steps:
      - uses: actions/checkout@v4
      - name: Release Build
        run: cargo build --release --locked --target=${{ matrix.job.target }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: clipshare-${{ matrix.job.target }}.exe
          path: target/${{ matrix.job.target }}/release/clipshare.exe